spring:
  application:
    name: Roster-Management-System-Backend
  datasource:
    url: jdbc:mysql://localhost:3306/rm_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: false

#Server
server:
  port: ${PORT:8080}

#Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui.path: /swagger-ui.html

#Jwt configuration
application:
  security:
    jwt:
      secret-key: qwertyuioplkjhgfdsazxcvbnmqwertyuioplkjhgfdsazxcvbnm
      access-token-expiration: 86400000
      refresh-token-expiration: 2592000000